version: 2.0

jobs:
  Py2:
      docker:
        - image: circleci/python:2.7
      steps: &steps
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install pkg-config python-dev
      - run:
          name: Install PyPI dependences
          command: |
            sudo pip install coverage pytest pytest-cov codecov codacy-coverage
            pip install -r requirements.txt --user

      - run:
          name: Testing
          command: |
            python --version ; pip --version ; pwd ; ls -l ; pip list
            coverage run -m py.test seqclust -v --doctest-modules --junitxml=test-reports/pytest_junit.xml
            coverage report
            coverage xml -o test-reports/coverage.xml
            export CODACY_PROJECT_TOKEN=6e89640b906343588b4ef1325c1eeedd && python-codacy-coverage -r test-reports/coverage.xml
            codecov

      - run:
          name: Install this package
          command: |
            python setup.py install --user --dry-run

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  Py3:
      docker:
        - image: circleci/python:3.6
      environment:
      steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - Py2
      - Py3
